{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quarkus-first.serviceAccountName" . }}
  labels:
{{ include "quarkus-first.labels" . | nindent 4 }}
{{- end -}}
