---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  labels:
    app: "first"
    version: "1.0.0-SNAPSHOT"
    group: "larsj"
  name: "first"
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "first"
    version: "1.0.0-SNAPSHOT"
    group: "larsj"
  name: "first"
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: "first"
    version: "1.0.0-SNAPSHOT"
    group: "larsj"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "first"
    version: "1.0.0-SNAPSHOT"
    group: "larsj"
  name: "first"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "first"
      version: "1.0.0-SNAPSHOT"
      group: "larsj"
  template:
    metadata:
      labels:
        app: "first"
        version: "1.0.0-SNAPSHOT"
        group: "larsj"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "kubernetes4lrn.azurecr.io/quarkus-first"
        imagePullPolicy: "IfNotPresent"
        name: "first"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
      serviceAccount: "first"
